language: node_js
node_js:
  - "6"
  - "8"
  - "10"
cache:
  yarn: true
install:
  - yarn global add coveralls greenkeeper-lockfile@1
  - yarn install
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
  - yarn test
  - cat coverage/lcov.info | coveralls
