language: node_js
node_js:
  - "6"
  - "8"
  - "9"
cache:
  yarn: true
install:
  - yarn global add codecov greenkeeper-lockfile@1
  - yarn install
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
  - yarn test
  - codecov
